on:
  push:
    branches:
      - 'master'
jobs:
  build_docker_image:
    runs-on: debian-latest
    steps:
      - 
        name: Check out
        uses: actions/checkout@v2
      -
        name: Log in to Docker Hub.
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - 
        name: Build and push image to Docker Hub
        id: buildx
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: wildsong/asterisk
          tags: latest
          addLatest: true
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      -
        name: Update the description on Docker Hub
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: wildsong/asterisk
          readme-filepath: ./README.docker.md
          short-description: ${{ github.event.repository.description }}
